Enabled: true
Spawning:
  BlockedMobs:
  - CAVE_SPIDER
  - CREEPER
  - GIANT
  - ZOMBIE
  - IRON_GOLEM
  - WITHER
  - SILVERFISH
  - SLIME
  - SNOWMAN
  - SPIDER
  - WITCH
  - MAGMA_CUBE
  - HORSE
  - BAT
  - PIG
  - COW
  - MUSHROOM_COW
  - CHICKEN
  - OCELOT
  - SHEEP
  - SQUID
  - VILLAGER
  - WOLF
  - ENDERMAN
  - ENDER_DRAGON
  - SHULKER
Leveling:
  StartLevel: 36
  DistancePerLevel: 13.3
