Naming:
  AlwaysShowName:
    Enabled: false
  Prefix:
    Format: '[Lvl #]'
    Enabled: true
  Suffix:
    Enabled: false
    Format: '#'
  Language: English
Leveling:
  MinLevel: 1
  MaxLevel: 400
  StartLevel: 1
  DistancePerLevel: 13.5
MobArena:
  WaveLeveling: false
  Enabled: false
  Multiplier: 0.1
  WavesPerLevel: 1.0
Stats:
  Health:
    Enabled: true
    Multiplier: 1.28
  Damage:
    Multiplier: 0.35
    Enabled: true
  Experience:
    Multiplier: 1.91
    Enabled: true
Spawning:
  LeveledSpawners: true
  BlockedMobs: []
  LeveledMobs:
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - ENDER_DRAGON
  - ENDERMAN
  - GHAST
  - GIANT
  - ZOMBIE
  - IRON_GOLEM
  - MAGMA_CUBE
  - WITHER
  - SILVERFISH
  - SKELETON
  - SLIME
  - SNOWMAN
  - SPIDER
  - WITCH
  - GUARDIAN
  - SHULKER
  - STRAY
  - HUSK
  - EVOKER
  - VEX
  - VINDICATOR
  - ELDER_GUARDIAN
  - COW
  - DONKEY
  - ENDERMITE
  - HORSE
  - LLAMA
  - MULE
  - MUSHROOM_COW
  - OCELOT
  - PIG
  - POLAR_BEAR
  - SHEEP
  - SKELETON_HORSE
  - SQUID
  - VILLAGER
  - WITHER_SKELETON
  - WOLF
  - ZOMBIE_HORSE
  - ZOMBIE_VILLAGER
  - BAT
  - CHICKEN
  - PIG_ZOMBIE
  - RABBIT
